apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      initContainers:
        - name: init-postgresql
          image: postgres:alpine
          command: ['sh', '-c', 'until pg_isready -h localhost -p 5432; do echo waiting for database; sleep 2; done; psql -U postgres -d postgres -c "CREATE DATABASE orderdb;"; psql -U postgres -d orderdb -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"']
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
      containers:
        - name: postgresql
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: "123456"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-data
          emptyDir: {}

