server:
  port: 8080
  allowOrigins:
    - "*"
  bodyLimit: "10M" # MiB
  timeout: 30 # Seconds

database:
  host: localhost
  port: 5433
  user: postgres
  password: 123456
  dbname: orderdb
  sslmode: disable
  schema: public