version: '3.8'

services:
  order_management_system:
    image: postgres:alpine
    container_name: order_management_system
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata: